# Generated by Django 3.1.7 on 2021-06-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_pic',
            old_name='profile_image',
            new_name='profile_pic',
        ),
    ]
