# Generated by Django 3.1.7 on 2021-06-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keepup.models


class Migration(migrations.Migration):

    dependencies = [
        ('keepup', '0002_auto_20210608_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_pic',
            field=models.ImageField(upload_to=keepup.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.AUTH_USER_MODEL),
        ),
    ]
