# Generated by Django 3.1.7 on 2021-06-19 14:16

from django.db import migrations, models
import keepup.models


class Migration(migrations.Migration):

    dependencies = [
        ('keepup', '0003_auto_20210609_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_pic',
            field=models.ImageField(default='/static/keepup/img/profile.jpg', upload_to=keepup.models.content_file_name),
        ),
    ]
