# Generated by Django 3.1.7 on 2021-06-19 14:19

from django.db import migrations, models
import keepup.models


class Migration(migrations.Migration):

    dependencies = [
        ('keepup', '0004_auto_20210619_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_pic',
            field=models.ImageField(upload_to=keepup.models.content_file_name),
        ),
    ]
